In [1]:
import pandas as pd
import os

import numpy as np
import math
import random
import itertools
import random
from sklearn.externals import joblib

import matplotlib.pyplot as plt
import math

/usr/local/lib/python3.7/dist-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)

In [2]:
label_file = "Dataset/new_height.csv"
data_df = pd.read_csv(label_file)
data_df

,1-2,1-3,1-4,1-5,1-6,1-7,1-8,1-9,1-10,1-11,...,64-66,64-67,64-68,65-66,65-67,65-68,66-67,66-68,67-68,height
0,16.124515,31.400637,47.518417,62.369865,77.491935,92.309263,104.446158,112.800709,118.190524,120.507261,...,8.000000,10.295630,14.212670,10.000000,14.764823,20.248457,5.099020,11.045361,6.000000,155.95
1,16.124515,32.557641,49.030603,64.031242,78.434686,92.135769,104.623133,115.108644,124.482931,129.402473,...,2.236068,6.403124,12.649111,12.165525,18.439089,25.317978,6.324555,13.152946,7.000000,156.70
2,11.045361,22.090722,33.241540,44.147480,54.083269,65.306967,75.292762,83.006024,87.045965,88.617154,...,7.000000,8.062258,11.401754,12.529964,16.155494,20.880613,4.000000,9.000000,5.000000,154.15
3,15.000000,30.149627,44.283180,59.682493,73.756356,86.683332,99.161484,106.470653,111.772090,109.343495,...,0.000000,5.099020,10.000000,8.062258,13.000000,18.027756,5.099020,10.000000,5.099020,155.45
4,21.000000,42.011903,61.294372,80.603970,96.767763,112.805142,128.631256,139.617334,147.410990,150.695056,...,9.055385,12.041595,17.888544,15.652476,22.135944,29.614186,7.000000,15.033296,8.062258,157.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,12.369317,25.495098,37.336309,50.089919,61.073726,71.700767,81.252692,86.977008,91.706052,91.268834,...,1.000000,4.000000,8.062258,7.280110,11.401754,15.524175,4.123106,8.246211,4.123106,154.30
482,24.083189,47.675990,69.634761,91.482239,112.946890,134.851770,154.738489,168.656456,176.954796,176.918060,...,10.198039,15.000000,22.825424,27.802878,38.078866,47.539457,11.180340,22.022716,11.045361,158.65
483,30.066593,60.000000,90.049986,119.339851,146.512798,169.858765,189.465036,204.188638,212.849712,217.278623,...,4.123106,11.661904,20.615528,25.079872,36.221541,46.097722,11.180340,21.023796,10.049876,160.95
484,24.020824,48.010416,76.791927,108.258949,140.687597,174.874241,206.886442,226.753170,238.371559,245.226426,...,19.235384,20.124612,23.021729,61.684682,72.801099,81.394103,12.041595,22.803509,11.180340,164.30
485,34.058773,70.007142,104.043260,137.615406,169.852878,198.917068,227.094694,245.637945,253.475837,250.049995,...,17.029386,23.430749,33.105891,39.115214,51.894123,64.560050,14.035669,29.154759,15.524175,162.55

In [3]:
data = data_df.drop(['height'], axis=1)

In [4]:
data

,1-2,1-3,1-4,1-5,1-6,1-7,1-8,1-9,1-10,1-11,...,64-65,64-66,64-67,64-68,65-66,65-67,65-68,66-67,66-68,67-68
0,16.124515,31.400637,47.518417,62.369865,77.491935,92.309263,104.446158,112.800709,118.190524,120.507261,...,8.246211,8.000000,10.295630,14.212670,10.000000,14.764823,20.248457,5.099020,11.045361,6.000000
1,16.124515,32.557641,49.030603,64.031242,78.434686,92.135769,104.623133,115.108644,124.482931,129.402473,...,13.000000,2.236068,6.403124,12.649111,12.165525,18.439089,25.317978,6.324555,13.152946,7.000000
2,11.045361,22.090722,33.241540,44.147480,54.083269,65.306967,75.292762,83.006024,87.045965,88.617154,...,11.045361,7.000000,8.062258,11.401754,12.529964,16.155494,20.880613,4.000000,9.000000,5.000000
3,15.000000,30.149627,44.283180,59.682493,73.756356,86.683332,99.161484,106.470653,111.772090,109.343495,...,8.062258,0.000000,5.099020,10.000000,8.062258,13.000000,18.027756,5.099020,10.000000,5.099020
4,21.000000,42.011903,61.294372,80.603970,96.767763,112.805142,128.631256,139.617334,147.410990,150.695056,...,13.152946,9.055385,12.041595,17.888544,15.652476,22.135944,29.614186,7.000000,15.033296,8.062258
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,12.369317,25.495098,37.336309,50.089919,61.073726,71.700767,81.252692,86.977008,91.706052,91.268834,...,7.615773,1.000000,4.000000,8.062258,7.280110,11.401754,15.524175,4.123106,8.246211,4.123106
482,24.083189,47.675990,69.634761,91.482239,112.946890,134.851770,154.738489,168.656456,176.954796,176.918060,...,25.000000,10.198039,15.000000,22.825424,27.802878,38.078866,47.539457,11.180340,22.022716,11.045361
483,30.066593,60.000000,90.049986,119.339851,146.512798,169.858765,189.465036,204.188638,212.849712,217.278623,...,26.076810,4.123106,11.661904,20.615528,25.079872,36.221541,46.097722,11.180340,21.023796,10.049876
484,24.020824,48.010416,76.791927,108.258949,140.687597,174.874241,206.886442,226.753170,238.371559,245.226426,...,61.032778,19.235384,20.124612,23.021729,61.684682,72.801099,81.394103,12.041595,22.803509,11.180340
485,34.058773,70.007142,104.043260,137.615406,169.852878,198.917068,227.094694,245.637945,253.475837,250.049995,...,32.249031,17.029386,23.430749,33.105891,39.115214,51.894123,64.560050,14.035669,29.154759,15.524175

In [5]:
data_arr = data.to_numpy()
data_arr

array([[ 16.1245155 ,  31.40063694,  47.51841748, ...,   5.09901951,
         11.04536102,   6.        ],
       [ 16.1245155 ,  32.55764119,  49.03060269, ...,   6.32455532,
         13.15294644,   7.        ],
       [ 11.04536102,  22.09072203,  33.24154028, ...,   4.        ,
          9.        ,   5.        ],
       ...,
       [ 30.06659276,  60.        ,  90.04998612, ...,  11.18033989,
         21.02379604,  10.04987562],
       [ 24.0208243 ,  48.01041554,  76.79192666, ...,  12.04159458,
         22.8035085 ,  11.18033989],
       [ 34.05877273,  70.00714249, 104.04326023, ...,  14.03566885,
         29.15475947,  15.5241747 ]])

In [6]:
label = data_df['height']
label

0      155.95
1      156.70
2      154.15
3      155.45
4      157.25
        ...
481    154.30
482    158.65
483    160.95
484    164.30
485    162.55
Name: height, Length: 486, dtype: float64

In [7]:
temp_label = label.to_numpy()
len(temp_label)

486

In [8]:
data_label = []
for i in temp_label:
    data_label.append(i.astype('int'))
data_label

[155,
 156,
 154,
 155,
 157,
 162,
 159,
 160,
 155,
 158,
 158,
 160,
 156,
 162,
 156,
 161,
 158,
 157,
 155,
 157,
 159,
 163,
 163,
 154,
 155,
 158,
 159,
 158,
 157,
 157,
 157,
 162,
 157,
 156,
 156,
 158,
 154,
 156,
 158,
 157,
 155,
 161,
 159,
 162,
 154,
 154,
 154,
 154,
 160,
 155,
 161,
 154,
 154,
 155,
 158,
 160,
 157,
 166,
 154,
 168,
 156,
 155,
 154,
 162,
 156,
 155,
 161,
 162,
 154,
 159,
 159,
 158,
 159,
 163,
 156,
 154,
 160,
 154,
 155,
 154,
 160,
 156,
 160,
 161,
 159,
 154,
 164,
 158,
 156,
 154,
 163,
 159,
 158,
 162,
 155,
 168,
 158,
 165,
 157,
 158,
 161,
 157,
 158,
 158,
 161,
 158,
 161,
 154,
 160,
 161,
 160,
 156,
 155,
 159,
 162,
 162,
 156,
 156,
 159,
 161,
 163,
 159,
 154,
 155,
 155,
 157,
 158,
 162,
 166,
 154,
 160,
 156,
 162,
 154,
 156,
 157,
 154,
 156,
 156,
 155,
 163,
 160,
 163,
 163,
 161,
 154,
 159,
 159,
 158,
 158,
 156,
 156,
 155,
 160,
 154,
 160,
 159,
 157,
 156,
 155,
 157,
 156,
 156,
 158,
 156,
 154,
 155,
 157,
 155,
 161,
 158,
 162,
 166,
 159,
 159,
 165,
 165,
 168,
 154,
 158,
 165,
 163,
 156,
 165,
 155,
 167,
 169,
 156,
 165,
 162,
 157,
 156,
 160,
 154,
 160,
 162,
 156,
 161,
 159,
 154,
 155,
 159,
 159,
 160,
 165,
 156,
 158,
 157,
 164,
 157,
 159,
 157,
 167,
 166,
 154,
 155,
 154,
 159,
 162,
 155,
 169,
 154,
 154,
 163,
 155,
 161,
 169,
 160,
 156,
 154,
 154,
 158,
 158,
 161,
 164,
 155,
 156,
 159,
 158,
 154,
 158,
 158,
 163,
 165,
 166,
 155,
 158,
 166,
 154,
 155,
 158,
 159,
 159,
 164,
 161,
 165,
 155,
 165,
 159,
 160,
 155,
 166,
 158,
 159,
 162,
 157,
 154,
 154,
 161,
 156,
 164,
 154,
 167,
 159,
 161,
 160,
 165,
 162,
 163,
 157,
 157,
 164,
 158,
 156,
 166,
 157,
 156,
 167,
 167,
 155,
 158,
 156,
 167,
 165,
 155,
 158,
 157,
 163,
 161,
 157,
 157,
 154,
 154,
 154,
 166,
 156,
 158,
 162,
 159,
 163,
 157,
 167,
 168,
 158,
 154,
 168,
 169,
 167,
 168,
 158,
 165,
 161,
 159,
 166,
 154,
 156,
 160,
 160,
 156,
 160,
 154,
 158,
 157,
 164,
 160,
 156,
 162,
 157,
 156,
 160,
 154,
 156,
 158,
 161,
 160,
 154,
 166,
 163,
 167,
 154,
 158,
 167,
 167,
 157,
 154,
 155,
 156,
 161,
 161,
 157,
 155,
 154,
 154,
 158,
 154,
 163,
 165,
 164,
 158,
 167,
 154,
 160,
 157,
 155,
 166,
 157,
 154,
 161,
 160,
 155,
 156,
 155,
 156,
 155,
 165,
 162,
 158,
 163,
 162,
 166,
 159,
 159,
 161,
 158,
 155,
 167,
 158,
 158,
 157,
 157,
 159,
 154,
 168,
 165,
 166,
 158,
 158,
 157,
 157,
 154,
 155,
 156,
 156,
 164,
 157,
 155,
 160,
 161,
 158,
 159,
 159,
 154,
 167,
 160,
 154,
 169,
 163,
 156,
 156,
 156,
 156,
 158,
 156,
 161,
 158,
 158,
 155,
 159,
 160,
 157,
 168,
 162,
 167,
 158,
 158,
 155,
 169,
 156,
 166,
 154,
 166,
 156,
 154,
 162,
 160,
 155,
 158,
 160,
 167,
 162,
 160,
 155,
 161,
 160,
 155,
 154,
 156,
 169,
 154,
 161,
 155,
 158,
 158,
 154,
 156,
 164,
 160,
 155,
 168,
 156,
 154,
 154,
 158,
 160,
 164,
 162]

In [9]:
from sklearn.feature_selection import SelectKBest, chi2

In [10]:
data_height_new = SelectKBest(chi2, k=5).fit_transform(data_arr, data_label)

In [11]:
data_height_new

array([[121.20231021, 124.48293056, 127.14165328, 126.3170614 ,
        126.24579201],
       [143.17122616, 136.89411967, 142.35870188, 140.43147795,
        143.05593312],
       [ 85.86617495,  88.02272434,  89.47066558,  86.92525525,
         88.48163651],
       ...,
       [243.87701819, 225.8583627 , 230.90257686, 226.49061791,
        231.39792566],
       [276.53752006, 284.15488734, 298.18786025, 295.70593501,
        306.72626233],
       [253.3396929 , 257.8410363 , 259.98846128, 251.54323684,
        250.44959573]])

In [12]:
index = 280
count = 0
for i in data_height_new[index]:
    for idx in range(len(data_arr[index])):
        if i == data_arr[index][idx]:
            count = count+1
            print(idx)
print(count)

465
517
575
576
632
5

In [19]:
selection_data = data_df.iloc[:, [575,2278]]
selection_data

          10-19  height
0    127.141653  155.95
1    142.358702  156.70
2     89.470666  154.15
3    115.693561  155.45
4    151.158857  157.25
..          ...     ...
481   88.294960  154.30
482  184.707877  158.65
483  230.902577  160.95
484  298.187860  164.30
485  259.988461  162.55

[486 rows x 2 columns]

In [20]:
selection_data.to_csv("selection_height_1.csv", encoding="utf-8", index=False)